CREATE DATABASE IF NOT EXISTS app_db;
USE app_db;

CREATE TABLE IF NOT EXISTS payloads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key_data VARCHAR(255) NOT NULL,
    value_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
